apiVersion: v1
kind: Service
metadata:
  name: llmops-rag-api-service
  namespace: llmops
  labels:
    app: rag-api
spec:
  type: NodePort
  selector:
    app: rag-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30800

---
apiVersion: v1
kind: Service
metadata:
  name: llmops-streamlit-service
  namespace: llmops
  labels:
    app: streamlit-ui
spec:
  type: NodePort
  selector:
    app: streamlit-ui
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
    nodePort: 30501

---
apiVersion: v1
kind: Service
metadata:
  name: llmops-api-loadbalancer
  namespace: llmops
  labels:
    app: rag-api
spec:
  type: LoadBalancer
  selector:
    app: rag-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
